# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Azhar
tagline:          'Just my 2 ¢ents'
url:              http://azkh93.github.io
shorturl:

author:
  name:           'Azhar Khan'
  url:            https://twitter.com/azhar937

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/azkh93/azkh93.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Projects: '/projects/'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
