# Dependencies
markdown:         kramdown
highlighter:      rouge


# Setup
title:            Azhar Khan
email:            azhar932@icloud.com
tagline:          'Just my 2 cents'
description:      "Data. Code. Design"
url:              http://localhost:4000
baseurl:
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Azhar Khan'
  url:            https://twitter.com/azhar937

paginate:         5
#paginate_path:    '/blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

github:
  repo:           https://github.com/azkh93/azkh93.github.io

disqus:
  shortname: azharkhan

google_analytics: UA-127874396-1


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
#sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
